#ifndef CLIENT_GAME_ASSET_ANIMATION_ID_H
#define CLIENT_GAME_ASSET_ANIMATION_ID_H

namespace Model {
enum class AnimationID { MUZZLE_FIRE = 0x00, BOMB_EXPLOSION = 0x01 };
};

#endif  // CLIENT_GAME_ASSET_ANIMATION_ID_H
