game:
  rounds: 2
  rounds_to_win: 6
  rounds_per_side: 5

  buy_time: 5
  warmup_time: 10
  post_round_time: 5
  round_time: 120
  round_won_money: 500
  round_lost_money: 250

  bomb_plant_time: 3
  bomb_defuse_time: 10
  bomb_explotion_time: 45

  kill_money: 200
  cost_primary_ammo: 100
  cost_secondary_ammo: 75

player:
  health: 100
  initial_money: 1000

weapons:
  knife:
    max_ammo: 0
    initial_ammo: 0
    damage_per_bullet: 20
    precision: 1.0
    cost: 0
    range: 1
    bullets_per_shot: 1
    fire_rate: 0.3
    dispersion: 0.0
    reload_time: 0

  glock:
    max_ammo: 120
    initial_ammo: 20
    damage_per_bullet: 25
    precision: 0.8
    cost: 0
    range: 4
    bullets_per_shot: 1
    fire_rate: 1
    dispersion: 0.03
    reload_time: 2.2

  ak-47:
    max_ammo: 90
    initial_ammo: 30
    damage_per_bullet: 20
    precision: 0.7
    cost: 1000
    range: 6
    bullets_per_shot: 3
    fire_rate: 0.2
    dispersion: 0.07
    reload_time: 2.5

  m3:
    max_ammo: 32
    initial_ammo: 8
    damage_per_bullet: 15
    precision: 0.6
    cost: 1100
    range: 3
    bullets_per_shot: 8
    fire_rate: 0.8
    dispersion: 20.0
    reload_time: 3.0

  awp:
    max_ammo: 30
    initial_ammo: 5
    damage_per_bullet: 100
    precision: 1.0
    cost: 1700
    range: 100
    bullets_per_shot: 1
    fire_rate: 1.3
    dispersion: 0
    reload_time: 3.7

fov:
  angle: 45
  ratio: 40
  opacity: 160

display:
  width: 580
  height: 400
